#!/bin/bash
# Copyright (C) 2019 The go-postgresql Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Usage Guide BenchBase
# https://github.com/cmu-db/benchbase?tab=readme-ov-file#usage-guide

BENCHBASE_DIR=benchbase

if [ ! -d ${BENCHBASE_DIR} ]; then
    git clone --depth 1 https://github.com/cmu-db/benchbase.git
    cd ${BENCHBASE_DIR}
    # ../benchbase-build-fix
    ./mvnw clean package -P postgres
    cd target
    tar xvzf benchbase-postgres.tgz
fi