#!/bin/bash
# Copyright (C) 2019 The go-postgresql Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Usage Guide BenchBase
# https://github.com/cmu-db/benchbase?tab=readme-ov-file#usage-guide

#BENCHBASE_GITURL=https://github.com/cmu-db
BENCHBASE_GITURL=https://github.com/cybergarage/
BENCHBASE_DIR=benchbase
BENCHBASE_TARGET=postgres
BENCHBASE_JAR=benchbase.jar
BENCHBASE_TARGET_DIR=${BENCHBASE_DIR}/target/benchbase-${BENCHBASE_TARGET}
BENCHBASE_TARGET_JAR=${BENCHBASE_TARGET_DIR}/${BENCHBASE_JAR}

if [ ! -f ${BENCHBASE_JAR} ]; then
    rm -rf ${BENCHBASE_DIR} lib data config scripts
    git clone --depth 1 ${BENCHBASE_GITURL}/benchbase.git
    cd ${BENCHBASE_DIR}
    ./mvnw package -P ${BENCHBASE_TARGET}
    cd target
    tar xvzf benchbase-${BENCHBASE_TARGET}.tgz
    cd ../..
    cp ${BENCHBASE_TARGET_JAR} .
    mv ${BENCHBASE_TARGET_DIR}/lib .
    mv ${BENCHBASE_TARGET_DIR}/data .
    mv ${BENCHBASE_TARGET_DIR}/config .
    mv ${BENCHBASE_TARGET_DIR}/scripts .
    cp config/${BENCHBASE_TARGET}/sample_tpcc_config.xml tpcc_config.xml
fi
echo "BenchBase setup completed."
java -jar ${BENCHBASE_JAR} -h