#!/bin/bash
# Copyright (C) 2019 Satoshi Konno. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

YCSB=ycsb-0.17.0
YCSB_JDBC_LIB=${YCSB}/jdbc-binding/lib

PGSQL_CONNECTOR=postgresql-42.5.4.jar

if [ ! -f ${PGSQL_CONNECTOR} ]; then
  wget https://jdbc.postgresql.org/download/${PGSQL_CONNECTOR}
fi

if [ ! -d ${YCSB} ]; then
  wget https://github.com/brianfrankcooper/YCSB/releases/download/0.17.0/${YCSB}.tar.gz
  tar xvfx ${YCSB}.tar.gz
fi

if [ ! -f ${YCSB_JDBC_LIB}/${PGSQL_CONNECTOR} ]; then
  cp ${PGSQL_CONNECTOR} ${YCSB_JDBC_LIB}
fi

export YCSB_ROOT=`pwd`/${YCSB}
export YCSB_DB_PROPERTIES=`pwd`/postgresqltest/ycsb/db.properties

echo "YCSB_ROOT          : ${YCSB_ROOT}"
echo "YCSB_DB_PROPERTIES : ${YCSB_DB_PROPERTIES}"
echo "PGSQL_CONNECTOR    : ${YCSB_JDBC_LIB}/${PGSQL_CONNECTOR}"