#!/bin/bash
set -eu

PG_CONTAINER_NAME="postgres"
PG_VERSION="16.10"
PG_USER="admin"
PG_PASSWORD="password"
PG_PORT=5432
BENCHBASE_JAR="benchbase.jar"

DUMP_FILE="benchbase-run-$(date +%Y%m%d%H%M%S).pcap"

echo "Starting PostgreSQL Docker container..."
docker run --name $PG_CONTAINER_NAME \
  -e POSTGRES_USER=$PG_USER \
  -e POSTGRES_PASSWORD=$PG_PASSWORD \
  -p $PG_PORT:5432 \
  -d postgres:$PG_VERSION

echo "Waiting for PostgreSQL to be ready..."
sleep 10

echo "Creating Benchbase database..."
PGPASSWORD=$PG_PASSWORD psql -h localhost -p $PG_PORT -U $PG_USER -c "CREATE DATABASE benchbase;"

echo "Starting tcpdump on port $PG_PORT..."
sudo tcpdump -i lo port $PG_PORT -w $DUMP_FILE &
TCPDUMP_PID=$!

echo "Running Benchbase TPC-C benchmark..."
make run

echo "Stopping tcpdump..."
sudo kill $TCPDUMP_PID

echo "Stopping and removing PostgreSQL Docker container..."
docker stop $PG_CONTAINER_NAME
docker rm $PG_CONTAINER_NAME

echo "Done! TCP dump saved as $DUMP_FILE"
